# Análisis Exploratorio y Procesamiento Básico de los Datos

Este notebook realiza un análisis exploratorio y procesamiento básico de los datos de opiniones turísticas usando módulos especializados con una estructura modular mejorada.

## Objetivo
- Cargar y procesar datos usando los módulos de procesamiento modular
- Realizar análisis exploratorio usando los módulos de exploración especializados
- Mantener código limpio, modular y bien organizado

## Nueva Estructura Modular
- **scripts/procesamiento/**: Clases especializadas para procesamiento de datos
  - `CargadorDatos`: Carga de archivos CSV
  - `LimpiadorDatos`: Limpieza y validación
  - `TransformadorDatos`: Transformaciones y creación de columnas
  - `ValidadorDatos`: Validación de calidad de datos
  
- **scripts/exploracion/**: Clases especializadas para análisis exploratorio
  - `AnalizadorGeneral`: Información general y valores nulos
  - `AnalizadorCategorico`: Distribuciones categóricas y calificaciones
  - `AnalizadorTemporal`: Análisis de fechas y tendencias temporales
  - `AnalizadorTexto`: Análisis de longitud y características de texto
  - `DetectorProblemas`: Detección de duplicados y contenidos mal ubicados

In [29]:
# Importar librerías necesarias
import pandas as pd
import numpy as np
import sys
import os
from pathlib import Path

# Agregar el directorio scripts al path para importar nuestros módulos
sys.path.append('../scripts')

# Importar nuestros módulos personalizados con la nueva estructura
from exploracion import (
    AnalizadorGeneral, 
    AnalizadorCategorico,
    AnalizadorTemporal,
    AnalizadorTexto,
    DetectorProblemas,
    resumen_ejecutivo,
    analisis_final_completo
)

from procesamiento import (
    CargadorDatos,
    LimpiadorDatos,
    TransformadorDatos,
    ValidadorDatos,
    procesar_dataset_completo
)

# Configuración para gráficos
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('default')
sns.set_palette("husl")
%matplotlib inline

print("✅ Librerías y módulos importados correctamente")
print("📁 Nueva estructura de módulos disponible:")
print("   - exploracion: AnalizadorGeneral, AnalizadorCategorico, AnalizadorTemporal, etc.")
print("   - procesamiento: CargadorDatos, LimpiadorDatos, TransformadorDatos, etc.")

✅ Librerías y módulos importados correctamente
📁 Nueva estructura de módulos disponible:
   - exploracion: AnalizadorGeneral, AnalizadorCategorico, AnalizadorTemporal, etc.
   - procesamiento: CargadorDatos, LimpiadorDatos, TransformadorDatos, etc.

## 1. Procesamiento Completo de Datos

Usando el pipeline completo de procesamiento que incluye: carga, limpieza de fechas, limpieza de OrigenAutor, completado de nulos, eliminación de duplicados, corrección de contenidos mal ubicados y creación de texto consolidado.

In [30]:
# Ejecutar el pipeline completo de procesamiento usando la nueva estructura
print("🚀 Iniciando procesamiento completo del dataset...")
print("="*60)

# El pipeline incluye todos los pasos de procesamiento:
# 1. Carga de datos de todas las ciudades
# 2. Conversión de fechas
# 3. Limpieza de OrigenAutor
# 4. Completado de valores nulos
# 5. Eliminación de duplicados
# 6. Corrección de contenidos mal ubicados
# 7. Creación de texto consolidado
# 8. Guardado del dataset final

df_opiniones = procesar_dataset_completo('../data')

if df_opiniones is not None:
    print(f"\n🎉 ¡Procesamiento exitoso!")
    print(f"📊 Dataset final: {len(df_opiniones):,} filas × {len(df_opiniones.columns)} columnas")
    print(f"📁 Guardado como: dataset_opiniones_consolidado.csv")
else:
    print("❌ Error en el procesamiento")

# Crear copia para análisis (preservar original)
df_analisis = df_opiniones.copy() if df_opiniones is not None else None
print(f"\n✅ Dataset de análisis creado: {len(df_analisis):,} filas" if df_analisis is not None else "❌ No se pudo crear dataset de análisis")

🚀 Iniciando procesamiento completo del dataset...
============================================================
================================================================================
             PIPELINE DE PROCESAMIENTO COMPLETO
================================================================================
✅ Directorios verificados: ../data/raw, ../data/processed

🔄 PASO 1: Cargando datos...
Ciudades encontradas en raw: ['cancun', 'cdmx']

Procesando ciudad: cancun
Archivos encontrados: 10
✓ cancun-xoximilco-cancun-by-xcaret.csv: 69 filas cargadas
✓ cancun-la-isla.csv: 70 filas cargadas
✓ cancun-acuario-interactivo.csv: 67 filas cargadas
✓ cancun-ventura-park.csv: 72 filas cargadas
✓ cancun-playa-delfines.csv: 70 filas cargadas
✓ cancun-avenida-kukulkan.csv: 72 filas cargadas
✓ cancun-museo-maya-de-cancun-y-zona-arqueologica-de-san-miguelito.csv: 64 filas cargadas
✓ cancun-las-plazas-outlet-cancun.csv: 72 filas cargadas
✓ cancun-puerto-maya-cancun.csv: 73 filas cargadas
✓ cancun-playa-tortugas.csv: 71 filas cargadas

Procesando ciudad: cdmx
Archivos encontrados: 10
✓ cdmx-paseo-de-la-reforma.csv: 61 filas cargadas
✓ cdmx-polanco.csv: 57 filas cargadas
✓ cdmx-museo-del-templo-mayor.csv: 53 filas cargadas
✓ cdmx-acuario-michin-ciudad-de-mexico.csv: 74 filas cargadas
✓ cdmx-mercado-de-artesanias-la-ciudadela.csv: 63 filas cargadas
✓ cdmx-basilica-de-la-virgen-guadalupe.csv: 68 filas cargadas
✓ cdmx-zocalo-de-la-ciudad-de-mexico.csv: 62 filas cargadas
✓ cdmx-jardines-flotantes-de-xochimilco.csv: 69 filas cargadas
✓ cdmx-palacio-de-bellas-artes.csv: 65 filas cargadas
✓ cdmx-museo-nacional-de-antropologia.csv: 53 filas cargadas

=== RESUMEN ===
Total de filas: 1325
Ciudades procesadas: 2
Atracciones procesadas: 20

🔄 PASO 2: Convirtiendo fechas...
=== CONVERSIÓN DE TIPOS DE DATOS PARA FECHAS ===
Ejemplos de fechas ANTES de conversión:
FechaOpinion: ['31 de agosto de 2025', '28 de agosto de 2025', '22 de agosto de 2025']
FechaEstadia: ['ago de 2025', 'ago de 2025', 'ago de 2025']

Convirtiendo fechas...

Ejemplos de fechas DESPUÉS de conversión:
FechaOpinion: [Timestamp('2025-08-31 00:00:00'), Timestamp('2025-08-28 00:00:00'), Timestamp('2025-08-22 00:00:00')]
Tipo: datetime64[ns]
FechaOpinion nulas: 0
FechaEstadia: [Timestamp('2025-08-01 00:00:00'), Timestamp('2025-08-01 00:00:00'), Timestamp('2025-08-01 00:00:00')]
Tipo: datetime64[ns]
FechaEstadia nulas: 0
✅ Conversión de fechas completada

🔄 PASO 3: Limpiando columna OrigenAutor...
=== LIMPIEZA DE COLUMNA OrigenAutor ===
Valores únicos antes de limpieza: 710
Valores únicos después de limpieza: 458
Valores eliminados (convertidos a None): 498

=== EJEMPLOS DE VALORES ELIMINADOS ===
'1 aporte' -> ELIMINADO (229 veces)
'Carlos S' -> ELIMINADO (5 veces)
'IVAN M' -> ELIMINADO (2 veces)
'Pamela L' -> ELIMINADO (2 veces)
'Monserrat L' -> ELIMINADO (2 veces)
'Academia O' -> ELIMINADO (2 veces)
'Abaca P' -> ELIMINADO (2 veces)
'Renata M' -> ELIMINADO (2 veces)
'CARLOS ANDRES A' -> ELIMINADO (2 veces)
'Aldo N' -> ELIMINADO (2 veces)
'Acoidan L' -> ELIMINADO (2 veces)
'Vs P' -> ELIMINADO (2 veces)
'Laura C' -> ELIMINADO (2 veces)
'Aidan Macias A' -> ELIMINADO (2 veces)
'Museo emblemático sobre la historia mesoamericana. Una gran pieza de arquitectura moderna con un extraordinario diseño museográfico. A pesar de ser el museo más emblemático de las culturas indígenas de México, las autoridades del MNAH han abandonado, sin ningún mantenimiento las áreas exteriores del museo como el estanque central principal, la fuente en el sótano que se puede apreciar desde la explanada de entrada y los jardines interiores de las salas de exposición. Les escribí hace tres meses, me dirigieron a otra área que hace alarde de negligencia y una total y vergonzosa indiferencia. Los propios jardineros se quejan de que les han pedido el equipo adecuado y no hay respuesta alguna. Esperemos que nuevas autoridades competentes se hagan cargo de una pieza tan relevante del patrimonio cultural de la arquitectura mexicana. LA PÁGINA DE TRIPADVISOR NO ME PERMITE SUBIR FOTOS PDF TOMADAS ESPECIALMENTE PARA ESTA OPINIÓN.' -> ELIMINADO (2 veces)
'Chapu C' -> ELIMINADO (2 veces)
'Shandra A' -> ELIMINADO (1 veces)
'Eliza L' -> ELIMINADO (1 veces)
'Karen T' -> ELIMINADO (1 veces)
'Liz M' -> ELIMINADO (1 veces)

=== VALORES CONSERVADOS (Top 20) ===
'Cancún, México': 42 veces
'Ciudad de México, México': 34 veces
'Buenos Aires, Argentina': 27 veces
'Bogotá, Colombia': 22 veces
'Montevideo, Uruguay': 20 veces
'Santiago, Chile': 11 veces
'Monterrey, México': 10 veces
'Estados Unidos': 10 veces
'Londres, UK': 9 veces
'Nueva York, Estado de Nueva York': 9 veces
'Medellín, Colombia': 9 veces
'Chicago, IL': 9 veces
'Madrid, España': 8 veces
'Playa del Carmen, México': 7 veces
'Cali, Colombia': 7 veces
'Córdoba, Argentina': 7 veces
'Houston, TX': 7 veces
'Lima, Perú': 7 veces
'Guayaquil, Ecuador': 7 veces
'Dallas, TX': 6 veces

=== VALIDACIÓN DE LA LIMPIEZA ===
Prueba de casos específicos:
'Pamela L' -> ❌ ELIMINADO
'Cifuentes E' -> ❌ ELIMINADO
'ALCIRA HAYDEE M' -> ❌ ELIMINADO
'1 aporte' -> ❌ ELIMINADO
'Puerto Rico' -> ✅ CONSERVADO
'Buenos Aires, Argentina' -> ✅ CONSERVADO
'San Juan, Puerto Rico' -> ✅ CONSERVADO
'Ciudad de México, México' -> ✅ CONSERVADO

=== REEMPLAZANDO COLUMNA ORIGINAL ===
✅ Columna OrigenAutor limpiada exitosamente
Valores únicos finales en OrigenAutor: 458

=== TOP 15 PAÍSES/LUGARES MÁS COMUNES (DESPUÉS DE LIMPIEZA) ===
'Cancún, México': 42 opiniones
'Ciudad de México, México': 34 opiniones
'Buenos Aires, Argentina': 27 opiniones
'Bogotá, Colombia': 22 opiniones
'Montevideo, Uruguay': 20 opiniones
'Santiago, Chile': 11 opiniones
'Monterrey, México': 10 opiniones
'Estados Unidos': 10 opiniones
'Londres, UK': 9 opiniones
'Nueva York, Estado de Nueva York': 9 opiniones
'Medellín, Colombia': 9 opiniones
'Chicago, IL': 9 opiniones
'Madrid, España': 8 opiniones
'Playa del Carmen, México': 7 opiniones
'Cali, Colombia': 7 opiniones

🔄 PASO 4: Completando valores nulos...
=== COMPLETANDO VALORES NULOS EN DATASET ===
Valores nulos ANTES de completar:
- Titulo: 8 nulos
- TipoViaje: 204 nulos
- OrigenAutor: 498 nulos

Valores nulos DESPUÉS de completar:
- Titulo: 0 nulos
- TipoViaje: 0 nulos
- OrigenAutor: 0 nulos

✅ Valores nulos completados exitosamente

=== DISTRIBUCIÓN DE VALORES AGREGADOS ===
'sin titulo': 8 registros
'desconocido': 204 registros
'anonimo': 498 registros

🔄 PASO 5: Eliminando duplicados...
=== ELIMINACIÓN DE DUPLICADOS ===
Filas completamente duplicadas encontradas: 11
Duplicados por título + review + ciudad + atracción: 11
Porcentaje de duplicados completos: 0.83%

🔄 Eliminando 11 filas duplicadas...
✅ Duplicados eliminados exitosamente
   Filas antes: 1,325
   Filas después: 1,314
   Filas eliminadas: 11

🔄 PASO 6: Corrigiendo contenidos mal ubicados...
=== CORRECCIÓN DE CONTENIDOS MAL UBICADOS ===
Examinando registros con contenido duplicado entre Titulo y OrigenAutor...

✅ Fila 282: 'Playa imperdible de México' -> Limpiado de Titulo (es lugar)
✅ Fila 705: 'Paseo de la Reforma, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 767: 'Colonia exclusiva de la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 801: 'El Beverly Hills de la ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 841: 'Una ventana a la rica historia de México. ¡Debo ver!' -> Limpiado de Titulo (es lugar)
✅ Fila 964: 'Mercado De Artesanias La Ciudadela, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 965: 'El mejor mercado de calidad en la ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 967: '"Artesanía típica de México"' -> Limpiado de Titulo (es lugar)
✅ Fila 1048: 'Basílica de Guadalupe soy de Colombia' -> Limpiado de Titulo (es lugar)
✅ Fila 1059: 'Nuestra primera parada obligatoria siempre que visitamos Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1063: 'Ella es la que hace a México, México.' -> Limpiado de Titulo (es lugar)
✅ Fila 1066: 'Viaje a México' -> Limpiado de Titulo (es lugar)
✅ Fila 1096: 'Zócalo, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 1114: 'El corazón de la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1120: 'Ciudad de México imperdible' -> Limpiado de Titulo (es lugar)
✅ Fila 1139: '¡Debo experimentar cuando visites la Ciudad de México!' -> Limpiado de Titulo (es lugar)
✅ Fila 1159: 'De lo mas deli en México' -> Limpiado de Titulo (es lugar)
✅ Fila 1181: 'Auténtico para la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1237: 'Palacio de Bellas Artes, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 1247: 'Un Palacio de Ensueño dentro de la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1313: 'Visita obligada en Ciudad de México' -> Limpiado de Titulo (es lugar)
=== RESUMEN DE CORRECCIONES ===
📊 Casos problemáticos encontrados: 21
✅ Correcciones automáticas realizadas: 21
⚠️  Casos que requieren revisión manual: 0

🔄 PASO 7: Creando texto consolidado...
=== CREACIÓN DE COLUMNA DE TEXTO CONSOLIDADO ===
Combinando todos los campos en una narrativa coherente...
Generando texto consolidado para cada registro...
✅ Columna 'TituloReview' creada exitosamente
Total de registros procesados: 1314

📊 ESTADÍSTICAS DE TEXTO CONSOLIDADO:
   • Longitud promedio: 340.8 caracteres
   • Longitud mínima: 106 caracteres
   • Longitud máxima: 2230 caracteres
   • Mediana: 238.0 caracteres

📝 EJEMPLOS DE TEXTO CONSOLIDADO:
================================================================================
• cdmx - palacio de bellas artes:
  'Murales Muchos murales y obras de arte de varios artistas mexicanos, incluido Diego Rivera, se muest...'

• cancun - la isla:
  'Estafadores La tienda YSL está haciendo una estafa. Compré un bonito bolso allí que dijeron que esta...'

• cdmx - mercado de artesanias la ciudadela:
  '¡Imperdible! Esta es una visita obligada si desea una oportunidad concentrada de compras de artes y ...'

• cancun - museo maya de cancun y zona arqueologica de san miguelito:
  'Museo Maya de Cancún El **Museo Maya de Cancún** es una institución cultural moderna dedicada a most...'

• cdmx - zocalo de la ciudad de mexico:
  'De lo mas importante de CDMX Enorme plaza en el Centro de Mexico, lugar de hechos historicos. Emocio...'


🔄 PASO 8: Aplicando capitalización a columnas categóricas...
✅ Capitalización aplicada a ciudades y atracciones

🔄 PASO 9: Guardando dataset procesado...
=== GUARDANDO DATASET PROCESADO ===
Columnas en el dataset final:
 1. Titulo
 2. Review
 3. TipoViaje
 4. Calificacion
 5. OrigenAutor
 6. FechaOpinion
 7. FechaEstadia
 8. Ciudad
 9. Atraccion
10. TituloReview

Dimensiones finales: (1314, 10)
Filas: 1,314
Columnas: 10

✅ Dataset final guardado como '../data/processed/dataset_opiniones_consolidado.csv'

📝 RESUMEN DE TEXTO CONSOLIDADO:
   • Registros con texto consolidado: 1314
   • Longitud promedio: 340.8 caracteres

🎉 PROCESAMIENTO COMPLETADO CON ÉXITO!
============================================================

🔄 PASO 10: Exportando datasets por ciudad...
📁 Directorio creado/verificado: ../data/processed/datasets_por_ciudad
💾 dataset_cancun.csv: 700 filas guardadas
📁 Ubicación: ../data/processed/datasets_por_ciudad/dataset_cancun.csv
💾 dataset_cdmx.csv: 614 filas guardadas
📁 Ubicación: ../data/processed/datasets_por_ciudad/dataset_cdmx.csv
✅ Exportación por ciudades completada en: ../data/processed/datasets_por_ciudad
� 2 datasets de ciudades creados

✅ PIPELINE DE PROCESAMIENTO COMPLETADO EXITOSAMENTE
📊 Dataset final: 1314 filas, 10 columnas

🎉 ¡Procesamiento exitoso!
📊 Dataset final: 1,314 filas × 10 columnas
📁 Guardado como: dataset_opiniones_consolidado.csv

✅ Dataset de análisis creado: 1,314 filas

Ejemplos de fechas DESPUÉS de conversión:
FechaOpinion: [Timestamp('2025-08-31 00:00:00'), Timestamp('2025-08-28 00:00:00'), Timestamp('2025-08-22 00:00:00')]
Tipo: datetime64[ns]
FechaOpinion nulas: 0
FechaEstadia: [Timestamp('2025-08-01 00:00:00'), Timestamp('2025-08-01 00:00:00'), Timestamp('2025-08-01 00:00:00')]
Tipo: datetime64[ns]
FechaEstadia nulas: 0
✅ Conversión de fechas completada

🔄 PASO 3: Limpiando columna OrigenAutor...
=== LIMPIEZA DE COLUMNA OrigenAutor ===
Valores únicos antes de limpieza: 710
Valores únicos después de limpieza: 458
Valores eliminados (convertidos a None): 498

=== EJEMPLOS DE VALORES ELIMINADOS ===
'1 aporte' -> ELIMINADO (229 veces)
'Carlos S' -> ELIMINADO (5 veces)
'IVAN M' -> ELIMINADO (2 veces)
'Pamela L' -> ELIMINADO (2 veces)
'Monserrat L' -> ELIMINADO (2 veces)
'Academia O' -> ELIMINADO (2 veces)
'Abaca P' -> ELIMINADO (2 veces)
'Renata M' -> ELIMINADO (2 veces)
'CARLOS ANDRES A' -> ELIMINADO (2 veces)
'Aldo N' -> ELIMINADO (2 veces)
'Acoidan L' -> ELIMINADO (2 veces)
'Vs P' -> ELIMINADO (2 veces)
'Laura C' -> ELIMINADO (2 veces)
'Aidan Macias A' -> ELIMINADO (2 veces)
'Museo emblemático sobre la historia mesoamericana. Una gran pieza de arquitectura moderna con un extraordinario diseño museográfico. A pesar de ser el museo más emblemático de las culturas indígenas de México, las autoridades del MNAH han abandonado, sin ningún mantenimiento las áreas exteriores del museo como el estanque central principal, la fuente en el sótano que se puede apreciar desde la explanada de entrada y los jardines interiores de las salas de exposición. Les escribí hace tres meses, me dirigieron a otra área que hace alarde de negligencia y una total y vergonzosa indiferencia. Los propios jardineros se quejan de que les han pedido el equipo adecuado y no hay respuesta alguna. Esperemos que nuevas autoridades competentes se hagan cargo de una pieza tan relevante del patrimonio cultural de la arquitectura mexicana. LA PÁGINA DE TRIPADVISOR NO ME PERMITE SUBIR FOTOS PDF TOMADAS ESPECIALMENTE PARA ESTA OPINIÓN.' -> ELIMINADO (2 veces)
'Chapu C' -> ELIMINADO (2 veces)
'Shandra A' -> ELIMINADO (1 veces)
'Eliza L' -> ELIMINADO (1 veces)
'Karen T' -> ELIMINADO (1 veces)
'Liz M' -> ELIMINADO (1 veces)

=== VALORES CONSERVADOS (Top 20) ===
'Cancún, México': 42 veces
'Ciudad de México, México': 34 veces
'Buenos Aires, Argentina': 27 veces
'Bogotá, Colombia': 22 veces
'Montevideo, Uruguay': 20 veces
'Santiago, Chile': 11 veces
'Monterrey, México': 10 veces
'Estados Unidos': 10 veces
'Londres, UK': 9 veces
'Nueva York, Estado de Nueva York': 9 veces
'Medellín, Colombia': 9 veces
'Chicago, IL': 9 veces
'Madrid, España': 8 veces
'Playa del Carmen, México': 7 veces
'Cali, Colombia': 7 veces
'Córdoba, Argentina': 7 veces
'Houston, TX': 7 veces
'Lima, Perú': 7 veces
'Guayaquil, Ecuador': 7 veces
'Dallas, TX': 6 veces

=== VALIDACIÓN DE LA LIMPIEZA ===
Prueba de casos específicos:
'Pamela L' -> ❌ ELIMINADO
'Cifuentes E' -> ❌ ELIMINADO
'ALCIRA HAYDEE M' -> ❌ ELIMINADO
'1 aporte' -> ❌ ELIMINADO
'Puerto Rico' -> ✅ CONSERVADO
'Buenos Aires, Argentina' -> ✅ CONSERVADO
'San Juan, Puerto Rico' -> ✅ CONSERVADO
'Ciudad de México, México' -> ✅ CONSERVADO

=== REEMPLAZANDO COLUMNA ORIGINAL ===
✅ Columna OrigenAutor limpiada exitosamente
Valores únicos finales en OrigenAutor: 458

=== TOP 15 PAÍSES/LUGARES MÁS COMUNES (DESPUÉS DE LIMPIEZA) ===
'Cancún, México': 42 opiniones
'Ciudad de México, México': 34 opiniones
'Buenos Aires, Argentina': 27 opiniones
'Bogotá, Colombia': 22 opiniones
'Montevideo, Uruguay': 20 opiniones
'Santiago, Chile': 11 opiniones
'Monterrey, México': 10 opiniones
'Estados Unidos': 10 opiniones
'Londres, UK': 9 opiniones
'Nueva York, Estado de Nueva York': 9 opiniones
'Medellín, Colombia': 9 opiniones
'Chicago, IL': 9 opiniones
'Madrid, España': 8 opiniones
'Playa del Carmen, México': 7 opiniones
'Cali, Colombia': 7 opiniones

🔄 PASO 4: Completando valores nulos...
=== COMPLETANDO VALORES NULOS EN DATASET ===
Valores nulos ANTES de completar:
- Titulo: 8 nulos
- TipoViaje: 204 nulos
- OrigenAutor: 498 nulos

Valores nulos DESPUÉS de completar:
- Titulo: 0 nulos
- TipoViaje: 0 nulos
- OrigenAutor: 0 nulos

✅ Valores nulos completados exitosamente

=== DISTRIBUCIÓN DE VALORES AGREGADOS ===
'sin titulo': 8 registros
'desconocido': 204 registros
'anonimo': 498 registros

🔄 PASO 5: Eliminando duplicados...
=== ELIMINACIÓN DE DUPLICADOS ===
Filas completamente duplicadas encontradas: 11
Duplicados por título + review + ciudad + atracción: 11
Porcentaje de duplicados completos: 0.83%

🔄 Eliminando 11 filas duplicadas...
✅ Duplicados eliminados exitosamente
   Filas antes: 1,325
   Filas después: 1,314
   Filas eliminadas: 11

🔄 PASO 6: Corrigiendo contenidos mal ubicados...
=== CORRECCIÓN DE CONTENIDOS MAL UBICADOS ===
Examinando registros con contenido duplicado entre Titulo y OrigenAutor...

✅ Fila 282: 'Playa imperdible de México' -> Limpiado de Titulo (es lugar)
✅ Fila 705: 'Paseo de la Reforma, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 767: 'Colonia exclusiva de la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 801: 'El Beverly Hills de la ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 841: 'Una ventana a la rica historia de México. ¡Debo ver!' -> Limpiado de Titulo (es lugar)
✅ Fila 964: 'Mercado De Artesanias La Ciudadela, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 965: 'El mejor mercado de calidad en la ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 967: '"Artesanía típica de México"' -> Limpiado de Titulo (es lugar)
✅ Fila 1048: 'Basílica de Guadalupe soy de Colombia' -> Limpiado de Titulo (es lugar)
✅ Fila 1059: 'Nuestra primera parada obligatoria siempre que visitamos Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1063: 'Ella es la que hace a México, México.' -> Limpiado de Titulo (es lugar)
✅ Fila 1066: 'Viaje a México' -> Limpiado de Titulo (es lugar)
✅ Fila 1096: 'Zócalo, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 1114: 'El corazón de la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1120: 'Ciudad de México imperdible' -> Limpiado de Titulo (es lugar)
✅ Fila 1139: '¡Debo experimentar cuando visites la Ciudad de México!' -> Limpiado de Titulo (es lugar)
✅ Fila 1159: 'De lo mas deli en México' -> Limpiado de Titulo (es lugar)
✅ Fila 1181: 'Auténtico para la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1237: 'Palacio de Bellas Artes, Ciudad de México en octubre' -> Limpiado de Titulo (es lugar)
✅ Fila 1247: 'Un Palacio de Ensueño dentro de la Ciudad de México' -> Limpiado de Titulo (es lugar)
✅ Fila 1313: 'Visita obligada en Ciudad de México' -> Limpiado de Titulo (es lugar)
=== RESUMEN DE CORRECCIONES ===
📊 Casos problemáticos encontrados: 21
✅ Correcciones automáticas realizadas: 21
⚠️  Casos que requieren revisión manual: 0

🔄 PASO 7: Creando texto consolidado...
=== CREACIÓN DE COLUMNA DE TEXTO CONSOLIDADO ===
Combinando todos los campos en una narrativa coherente...
Generando texto consolidado para cada registro...
✅ Columna 'TituloReview' creada exitosamente
Total de registros procesados: 1314

📊 ESTADÍSTICAS DE TEXTO CONSOLIDADO:
   • Longitud promedio: 340.8 caracteres
   • Longitud mínima: 106 caracteres
   • Longitud máxima: 2230 caracteres
   • Mediana: 238.0 caracteres

📝 EJEMPLOS DE TEXTO CONSOLIDADO:
================================================================================
• cdmx - palacio de bellas artes:
  'Murales Muchos murales y obras de arte de varios artistas mexicanos, incluido Diego Rivera, se muest...'

• cancun - la isla:
  'Estafadores La tienda YSL está haciendo una estafa. Compré un bonito bolso allí que dijeron que esta...'

• cdmx - mercado de artesanias la ciudadela:
  '¡Imperdible! Esta es una visita obligada si desea una oportunidad concentrada de compras de artes y ...'

• cancun - museo maya de cancun y zona arqueologica de san miguelito:
  'Museo Maya de Cancún El **Museo Maya de Cancún** es una institución cultural moderna dedicada a most...'

• cdmx - zocalo de la ciudad de mexico:
  'De lo mas importante de CDMX Enorme plaza en el Centro de Mexico, lugar de hechos historicos. Emocio...'



/home/victorwkey/analisis-automatizado-de-opiniones-turisticas/notebooks/../scripts/procesamiento/limpieza_datos.py:130: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df['Titulo'].fillna('sin titulo', inplace=True)
/home/victorwkey/analisis-automatizado-de-opiniones-turisticas/notebooks/../scripts/procesamiento/limpieza_datos.py:132: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df['TipoViaje'].fillna('desconocido', inplace=True)
/home/victorwkey/analisis-automatizado-de-opiniones-turisticas/notebooks/../scripts/procesamiento/limpieza_datos.py:134: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df['OrigenAutor'].fillna('anonimo', inplace=True)

In [31]:
# Verificación rápida del dataset procesado
if df_opiniones is not None:
    print("=== VERIFICACIÓN RÁPIDA DEL DATASET PROCESADO ===")
    print(f"Forma del dataset: {df_opiniones.shape}")
    print(f"Columnas disponibles:")
    for i, col in enumerate(df_opiniones.columns, 1):
        print(f"  {i:2d}. {col}")
    
    print(f"\nMuestra de datos (primeras 5 filas):")
    display(df_opiniones.head())
    
    print(f"\nEstado de valores nulos:")
    nulos = df_opiniones.isnull().sum()
    for col, nulo in nulos.items():
        estado = "✅" if nulo == 0 else "⚠️"
        print(f"  {estado} {col}: {nulo} nulos")
else:
    print("❌ No hay datos para verificar")

=== VERIFICACIÓN RÁPIDA DEL DATASET PROCESADO ===
Forma del dataset: (1314, 10)
Columnas disponibles:
   1. Titulo
   2. Review
   3. TipoViaje
   4. Calificacion
   5. OrigenAutor
   6. FechaOpinion
   7. FechaEstadia
   8. Ciudad
   9. Atraccion
  10. TituloReview

Muestra de datos (primeras 5 filas):

,Titulo,Review,TipoViaje,Calificacion,OrigenAutor,FechaOpinion,FechaEstadia,Ciudad,Atraccion,TituloReview
0,Divertido y emocionante,Se organizó el transporte. La recepción en el ...,Pareja,5,anonimo,2025-08-31,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Divertido y emocionante Se organizó el transpo...
1,Increíble,"Ninguno, me encantó toda la experiencias fue i...",Pareja,5,anonimo,2025-08-28,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,"Increíble Ninguno, me encantó toda la experien..."
2,Xochimilco excelente experiencia,Joss y Roberto dieron muy buen servicio y ambi...,Pareja,5,anonimo,2025-08-22,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Xochimilco excelente experiencia Joss y Robert...
3,Xoximilco increible experiencia,Fue una experiencia maravillosa el ambiente de...,Amigos,5,anonimo,2025-08-21,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Xoximilco increible experiencia Fue una experi...
4,Xochimilco tiene el mejor ambiente de fiesta!!,Fui con mis amigos a celebrar mi cumpleaños y ...,Amigos,5,María Elena F,2025-08-19,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Xochimilco tiene el mejor ambiente de fiesta!!...

Estado de valores nulos:
  ✅ Titulo: 0 nulos
  ✅ Review: 0 nulos
  ✅ TipoViaje: 0 nulos
  ✅ Calificacion: 0 nulos
  ✅ OrigenAutor: 0 nulos
  ✅ FechaOpinion: 0 nulos
  ✅ FechaEstadia: 0 nulos
  ✅ Ciudad: 0 nulos
  ✅ Atraccion: 0 nulos
  ✅ TituloReview: 0 nulos

## 2. Análisis Exploratorio usando Módulos Especializados

Ahora usaremos las funciones del módulo de exploración para realizar análisis descriptivos sin modificar los datos.

In [32]:
# Análisis de información general del dataset usando la nueva estructura
if df_analisis is not None:
    analizador_general = AnalizadorGeneral(df_analisis)
    analizador_general.analizar_informacion_general()
else:
    print("❌ No hay datos para analizar")

=== INFORMACIÓN GENERAL DEL DATASET ===
Dimensiones: (1314, 10)
Número de filas: 1,314
Número de columnas: 10

Columnas del dataset:
1. Titulo
2. Review
3. TipoViaje
4. Calificacion
5. OrigenAutor
6. FechaOpinion
7. FechaEstadia
8. Ciudad
9. Atraccion
10. TituloReview

=== TIPOS DE DATOS ===
<class 'pandas.core.frame.DataFrame'>
Index: 1314 entries, 0 to 1324
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Titulo        1314 non-null   object
 1   Review        1314 non-null   object
 2   TipoViaje     1314 non-null   object
 3   Calificacion  1314 non-null   int64
 4   OrigenAutor   1314 non-null   object
 5   FechaOpinion  1314 non-null   datetime64[ns]
 6   FechaEstadia  1314 non-null   datetime64[ns]
 7   Ciudad        1314 non-null   object
 8   Atraccion     1314 non-null   object
 9   TituloReview  1314 non-null   object
dtypes: datetime64[ns](2), int64(1), object(7)
memory usage: 145.2+ KB

In [33]:
# Análisis de valores nulos y calidad de datos usando la nueva estructura
if df_analisis is not None:
    analizador_general = AnalizadorGeneral(df_analisis)
    
    analizador_general.analizar_valores_nulos()
    print("\n")
    analizador_general.analizar_duplicados()
else:
    print("❌ No hay datos para analizar")

=== ANÁLISIS DE VALORES NULOS ===
              Valores_Nulos  Porcentaje
Titulo                    0         0.0
Review                    0         0.0
TipoViaje                 0         0.0
Calificacion              0         0.0
OrigenAutor               0         0.0
FechaOpinion              0         0.0
FechaEstadia              0         0.0
Ciudad                    0         0.0
Atraccion                 0         0.0
TituloReview              0         0.0


=== ANÁLISIS DE DUPLICADOS ===
Filas completamente duplicadas encontradas: 0
Duplicados por título + review + ciudad + atracción: 0
Filas completamente duplicadas encontradas: 0
Duplicados por título + review + ciudad + atracción: 0

In [34]:
# Detección de contenidos mal ubicados usando la nueva estructura
if df_analisis is not None:
    detector_problemas = DetectorProblemas(df_analisis)
    resultados, problemas = detector_problemas.detectar_contenidos_mal_ubicados()
else:
    print("❌ No hay datos para detectar problemas")

=== ANÁLISIS AVANZADO DE CONTENIDOS MAL UBICADOS ===
Detectando cuando el contenido de una columna aparece en otra columna diferente...
Analizando columnas de texto: ['Titulo', 'Review', 'TipoViaje', 'OrigenAutor']
Longitud mínima de texto: 10 caracteres

=== RESUMEN DEL ANÁLISIS ===
✅ No se encontraron contenidos mal ubicados entre columnas
   El dataset parece estar bien estructurado en este aspecto

## 3. Análisis Descriptivo por Categorías

In [35]:
# Análisis de distribuciones categóricas usando la nueva estructura
if df_analisis is not None:
    analizador_categorico = AnalizadorCategorico(df_analisis)
    analizador_categorico.analizar_distribuciones_categoricas()
else:
    print("❌ No hay datos para analizar")

=== DISTRIBUCIÓN POR CIUDADES ===
Ciudad
Cancun    700
Cdmx      614
Name: count, dtype: int64

Porcentaje por ciudad:
Ciudad
Cancun    53.27
Cdmx      46.73
Name: count, dtype: float64

=== TOP 10 ATRACCIONES CON MÁS OPINIONES ===
Atraccion
Acuario Michin Ciudad De Mexico     74
Puerto Maya Cancun                  73
Ventura Park                        72
Las Plazas Outlet Cancun            72
Avenida Kukulkan                    72
Playa Tortugas                      71
La Isla                             70
Playa Delfines                      70
Jardines Flotantes De Xochimilco    69
Xoximilco Cancun By Xcaret          69
Name: count, dtype: int64

=== ANÁLISIS DE TIPOS DE VIAJE ===
TipoViaje
Familia        471
Pareja         338
desconocido    203
Amigos         175
Solitario      115
Negocios        12
Name: count, dtype: int64

Porcentaje por tipo de viaje:
TipoViaje
Familia        35.84
Pareja         25.72
desconocido    15.45
Amigos         13.32
Solitario       8.75
Negocios        0.91
Name: count, dtype: float64

In [36]:
# Análisis de calificaciones usando la nueva estructura
if df_analisis is not None:
    analizador_categorico = AnalizadorCategorico(df_analisis)
    analizador_categorico.analizar_calificaciones()
else:
    print("❌ No hay datos para analizar")

=== ANÁLISIS DE CALIFICACIONES ===
Estadísticas descriptivas de calificaciones:
count    1314.000000
mean        4.259513
std         1.131999
min         1.000000
25%         4.000000
50%         5.000000
75%         5.000000
max         5.000000
Name: Calificacion, dtype: float64

Distribución de calificaciones:
Calificacion
1     78
2     34
3    145
4    269
5    788
Name: count, dtype: int64

Calificación promedio general: 4.26

## 4. Análisis de Longitud de Textos y Temporal

In [37]:
# Análisis de longitud de textos y temporal usando la nueva estructura
if df_analisis is not None:
    analizador_texto = AnalizadorTexto(df_analisis)
    analizador_temporal = AnalizadorTemporal(df_analisis)
    
    analizador_texto.analizar_longitud_textos()
    
    print("\n")
    
    # Análisis temporal
    analizador_temporal.analizar_temporal()
else:
    print("❌ No hay datos para analizar")

=== ANÁLISIS DE LONGITUD DE TÍTULOS ===
count    1314.000000
mean       27.125571
std        19.970166
min         2.000000
25%        13.000000
50%        21.000000
75%        34.750000
max       129.000000
Name: Titulo, dtype: float64

=== ANÁLISIS DE LONGITUD DE REVIEWS ===
count    1314.000000
mean      312.919330
std       276.529729
min       100.000000
25%       145.000000
50%       203.000000
75%       366.750000
max      2162.000000
Name: Review, dtype: float64

=== NÚMERO DE PALABRAS EN REVIEWS ===
count    1314.000000
mean       53.611872
std        47.721281
min        11.000000
25%        25.000000
50%        35.000000
75%        63.000000
max       361.000000
Name: Review, dtype: float64


=== ANÁLISIS TEMPORAL DE OPINIONES ===
Ejemplos de fechas en el dataset:
[Timestamp('2025-08-31 00:00:00'), Timestamp('2025-08-28 00:00:00'), Timestamp('2025-08-22 00:00:00'), Timestamp('2025-08-21 00:00:00'), Timestamp('2025-08-19 00:00:00'), Timestamp('2025-08-19 00:00:00'), Timestamp('2025-08-17 00:00:00'), Timestamp('2025-08-12 00:00:00'), Timestamp('2025-08-12 00:00:00'), Timestamp('2025-08-09 00:00:00')]

Fechas únicas de opinión: 752

Top 10 fechas con más opiniones:
FechaOpinion
2024-07-22    10
2024-09-12    10
2024-09-04     9
2024-09-11     8
2025-08-14     8
2025-07-24     8
2025-08-31     7
2025-07-15     7
2025-06-10     6
2024-08-19     6
Name: count, dtype: int64

## 5. Resumen Ejecutivo

In [38]:
# Resumen ejecutivo del análisis usando la nueva estructura
if df_analisis is not None:
    resumen_ejecutivo(df_analisis)
else:
    print("❌ No hay datos para generar resumen")

============================================================
                    RESUMEN EJECUTIVO
============================================================
📊 VOLUMEN DE DATOS:
   • Total de opiniones: 1,314
   • Ciudades analizadas: 2
   • Atracciones totales: 20

🏙️ DISTRIBUCIÓN POR CIUDADES:
   • CANCUN: 700 opiniones (53.3%)
   • CDMX: 614 opiniones (46.7%)

⭐ CALIFICACIONES:
   • Promedio general: 4.26/5
   • Mediana: 5.0/5

👥 TIPO DE VIAJE:
   • Más común: Familia

🔍 CALIDAD DE DATOS:
   • Duplicados completos: 0
   • Sin valores nulos detectados

✅ Dataset listo para análisis más profundos!
============================================================

## 6. Análisis Final Completo

In [39]:
# Análisis final completo del dataset limpio usando la nueva estructura
if df_analisis is not None:
    analisis_final_completo(df_analisis)
else:
    print("❌ No hay datos para análisis final")

================================================================================
                     ANÁLISIS FINAL COMPLETO
                    DATASET COMPLETAMENTE LIMPIO
================================================================================

📊 RESUMEN GENERAL:
   • Total de registros finales: 1,314
   • Total de columnas: 10
   • Ciudades: 2
   • Atracciones: 20

🔍 CALIDAD DE DATOS FINAL:
   • Valores nulos totales: 0
   • Duplicados restantes: 0
   • Integridad de datos: ✅ PERFECTA

🏙️ DISTRIBUCIÓN FINAL POR CIUDADES:
   • CANCUN: 700 (53.3%)
   • CDMX: 614 (46.7%)

⭐ ANÁLISIS DE CALIFICACIONES FINAL:
   • Promedio general: 4.26/5
   • Mediana: 5.0/5
   • Moda: 5/5
   • Desviación estándar: 1.13

   Distribución de calificaciones:
     1 estrellas: 78 (5.9%)
     2 estrellas: 34 (2.6%)
     3 estrellas: 145 (11.0%)
     4 estrellas: 269 (20.5%)
     5 estrellas: 788 (60.0%)

👥 TIPOS DE VIAJE FINAL:
   • Familia: 471 (35.8%)
   • Pareja: 338 (25.7%)
   • desconocido: 203 (15.4%)
   • Amigos: 175 (13.3%)
   • Solitario: 115 (8.8%)
   • Negocios: 12 (0.9%)

🏆 TOP 5 ATRACCIONES POR CALIFICACIÓN PROMEDIO:
   • Mediana: 5.0/5
   • Moda: 5/5
   • Desviación estándar: 1.13

   Distribución de calificaciones:
     1 estrellas: 78 (5.9%)
     2 estrellas: 34 (2.6%)
     3 estrellas: 145 (11.0%)
     4 estrellas: 269 (20.5%)
     5 estrellas: 788 (60.0%)

👥 TIPOS DE VIAJE FINAL:
   • Familia: 471 (35.8%)
   • Pareja: 338 (25.7%)
   • desconocido: 203 (15.4%)
   • Amigos: 175 (13.3%)
   • Solitario: 115 (8.8%)
   • Negocios: 12 (0.9%)

🏆 TOP 5 ATRACCIONES POR CALIFICACIÓN PROMEDIO:
   • Xoximilco Cancun By Xcaret (Cancun): 4.90/5 (69 opiniones)
   • Puerto Maya Cancun (Cancun): 4.88/5 (73 opiniones)
   • Museo Nacional De Antropologia (Cdmx): 4.84/5 (43 opiniones)
   • Basilica De La Virgen Guadalupe (Cdmx): 4.78/5 (68 opiniones)
   • Museo Del Templo Mayor (Cdmx): 4.75/5 (53 opiniones)

🌍 TOP 10 PAÍSES/REGIONES DE ORIGEN:
   • Cancún, México: 41 (3.1%)
   • Ciudad de México, México: 32 (2.4%)
   • Buenos Aires, Argentina: 27 (2.1%)
   • Bogotá, Colombia: 21 (1.6%)
   • Montevideo, Uruguay: 19 (1.4%)
   • Santiago, Chile: 11 (0.8%)
   • Estados Unidos: 10 (0.8%)
   • Monterrey, México: 10 (0.8%)
   • Nueva York, Estado de Nueva York: 9 (0.7%)
   • Londres, UK: 9 (0.7%)

================================================================================
✅ ANÁLISIS FINAL COMPLETADO
🎯 Dataset completamente limpio y listo para análisis avanzados
📊 Calidad de datos: EXCELENTE
================================================================================
   • Xoximilco Cancun By Xcaret (Cancun): 4.90/5 (69 opiniones)
   • Puerto Maya Cancun (Cancun): 4.88/5 (73 opiniones)
   • Museo Nacional De Antropologia (Cdmx): 4.84/5 (43 opiniones)
   • Basilica De La Virgen Guadalupe (Cdmx): 4.78/5 (68 opiniones)
   • Museo Del Templo Mayor (Cdmx): 4.75/5 (53 opiniones)

🌍 TOP 10 PAÍSES/REGIONES DE ORIGEN:
   • Cancún, México: 41 (3.1%)
   • Ciudad de México, México: 32 (2.4%)
   • Buenos Aires, Argentina: 27 (2.1%)
   • Bogotá, Colombia: 21 (1.6%)
   • Montevideo, Uruguay: 19 (1.4%)
   • Santiago, Chile: 11 (0.8%)
   • Estados Unidos: 10 (0.8%)
   • Monterrey, México: 10 (0.8%)
   • Nueva York, Estado de Nueva York: 9 (0.7%)
   • Londres, UK: 9 (0.7%)

================================================================================
✅ ANÁLISIS FINAL COMPLETADO
🎯 Dataset completamente limpio y listo para análisis avanzados
📊 Calidad de datos: EXCELENTE
================================================================================

In [40]:
# Mostrar muestra final del dataset
if df_analisis is not None:
    print("=== MUESTRA FINAL DEL DATASET ===")
    display(df_analisis.head())
    
    print(f"\n=== RESUMEN FINAL ===")
    print(f"✅ Análisis exploratorio completado exitosamente")
    print(f"📊 Dataset procesado: {len(df_analisis):,} filas × {len(df_analisis.columns)} columnas")
    print(f"🗂️  Archivo guardado: dataset_opiniones_consolidado.csv")
    
    if 'texto_consolidado' in df_analisis.columns:
        print(f"📝 Texto consolidado disponible para análisis de sentimientos")
        longitud_promedio = df_analisis['texto_consolidado'].str.len().mean()
        print(f"📏 Longitud promedio del texto: {longitud_promedio:.1f} caracteres")
    
    print(f"\n🎯 Dataset listo para:")
    print(f"   • Análisis de sentimientos")
    print(f"   • Modelado de machine learning")
    print(f"   • Visualizaciones avanzadas")
    print(f"   • Reportes automáticos")
else:
    print("❌ No se pudo completar el análisis")

=== MUESTRA FINAL DEL DATASET ===

,Titulo,Review,TipoViaje,Calificacion,OrigenAutor,FechaOpinion,FechaEstadia,Ciudad,Atraccion,TituloReview
0,Divertido y emocionante,Se organizó el transporte. La recepción en el ...,Pareja,5,anonimo,2025-08-31,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Divertido y emocionante Se organizó el transpo...
1,Increíble,"Ninguno, me encantó toda la experiencias fue i...",Pareja,5,anonimo,2025-08-28,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,"Increíble Ninguno, me encantó toda la experien..."
2,Xochimilco excelente experiencia,Joss y Roberto dieron muy buen servicio y ambi...,Pareja,5,anonimo,2025-08-22,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Xochimilco excelente experiencia Joss y Robert...
3,Xoximilco increible experiencia,Fue una experiencia maravillosa el ambiente de...,Amigos,5,anonimo,2025-08-21,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Xoximilco increible experiencia Fue una experi...
4,Xochimilco tiene el mejor ambiente de fiesta!!,Fui con mis amigos a celebrar mi cumpleaños y ...,Amigos,5,María Elena F,2025-08-19,2025-08-01,Cancun,Xoximilco Cancun By Xcaret,Xochimilco tiene el mejor ambiente de fiesta!!...

=== RESUMEN FINAL ===
✅ Análisis exploratorio completado exitosamente
📊 Dataset procesado: 1,314 filas × 10 columnas
🗂️  Archivo guardado: dataset_opiniones_consolidado.csv

🎯 Dataset listo para:
   • Análisis de sentimientos
   • Modelado de machine learning
   • Visualizaciones avanzadas
   • Reportes automáticos

## 7. Generación de Datasets por Ciudad

Creación de datasets separados por ciudad con las columnas específicas solicitadas: Titulo, Review, Calificacion, FechaEstadia, Ciudad, Atraccion, TituloReview

In [41]:
# Exportar datasets separados por ciudad - VERSIÓN MODULAR
from procesamiento import exportar_datasets_por_ciudad, verificar_datasets_creados

print("🚀 Iniciando exportación de datasets por ciudad...")
print("="*50)

try:
    # Usar la función modular optimizada para exportar
    directorio_ciudades = exportar_datasets_por_ciudad(df_opiniones, '../data')
    
    print(f"\n✅ EXPORTACIÓN COMPLETADA EXITOSAMENTE")
    print(f"📁 Ubicación: {directorio_ciudades}")
    
    # Verificar y obtener estadísticas de los datasets creados usando función modular
    datasets_creados = verificar_datasets_creados(directorio_ciudades, df_opiniones)
    
    print(f"\n🎯 ¡{len(datasets_creados)} datasets de ciudades listos para análisis!")
    
except Exception as e:
    print(f"❌ Error durante la exportación: {e}")
    print("🔄 Revisar configuración del directorio de datos...")
    
    # Variables para compatibilidad con la siguiente celda
    datasets_creados = []
    directorio_ciudades = '../data/processed/datasets_por_ciudad'

🚀 Iniciando exportación de datasets por ciudad...
==================================================
📁 Directorio creado/verificado: ../data/processed/datasets_por_ciudad
💾 dataset_cancun.csv: 700 filas guardadas
📁 Ubicación: ../data/processed/datasets_por_ciudad/dataset_cancun.csv
💾 dataset_cdmx.csv: 614 filas guardadas
📁 Ubicación: ../data/processed/datasets_por_ciudad/dataset_cdmx.csv
✅ Exportación por ciudades completada en: ../data/processed/datasets_por_ciudad
� 2 datasets de ciudades creados

✅ EXPORTACIÓN COMPLETADA EXITOSAMENTE
📁 Ubicación: ../data/processed/datasets_por_ciudad

📊 RESUMEN:
   • Archivos encontrados: 2
   • Total de filas en dataset principal: 1,314
   • Archivos de ciudades válidos: 2

📋 ARCHIVOS DE CIUDADES GENERADOS:
   📄 Cancun: dataset_cancun.csv (531.7 KB)
   📄 Cdmx: dataset_cdmx.csv (465.8 KB)

🎯 ¡2 datasets de ciudades listos para análisis!

In [42]:
# Mostrar resumen detallado de los datasets creados - VERSIÓN OPTIMIZADA
from procesamiento import mostrar_resumen_detallado_datasets, resumen_rapido_datasets

if df_opiniones is not None and 'datasets_creados' in locals() and datasets_creados:
    # Usar función modular optimizada (sin lecturas innecesarias de archivos)
    mostrar_resumen_detallado_datasets(datasets_creados, df_opiniones)
    
elif df_opiniones is not None:
    print("⚠️ Los datasets por ciudad no se crearon correctamente")
    print("💡 Ejecutando verificación rápida...")
    
    # Usar resumen rápido en lugar de verificación lenta
    if 'directorio_ciudades' in locals():
        try:
            # Función ultra-rápida que no lee archivos CSV
            resumen = resumen_rapido_datasets(directorio_ciudades, df_opiniones)
            
            if resumen.get("total_archivos", 0) > 0:
                print(f"✅ Se encontraron {resumen['total_archivos']} archivos CSV")
                print("📁 Los datasets están disponibles para análisis")
            else:
                print("❌ No se encontraron archivos CSV válidos")
                
        except Exception as e:
            print(f"❌ Error en verificación rápida: {e}")
            print("💡 Intenta ejecutar nuevamente la celda de exportación")
else:
    print("❌ No hay datos principales disponibles para verificar")

print(f"\n✅ Verificación completada - Los datasets están listos para análisis de sentimientos")

=== RESUMEN DETALLADO DE DATASETS POR CIUDAD ===

📊 Estadísticas generales:
   • Total de ciudades: 2
   • Total de filas en dataset principal: 1,314
   • Ciudades reales: Cancun, Cdmx

📋 Detalle por ciudad:
    1. Cdmx            → dataset_cdmx.csv
       📊 614 filas ( 46.7%) | 10 columnas | 465.8 KB
    2. Cancun          → dataset_cancun.csv
       📊 700 filas ( 53.3%) | 10 columnas | 531.7 KB

🔍 VERIFICACIÓN DE INTEGRIDAD:
   • Archivos creados correctamente: 2/2
   • Total filas calculadas: 1,314
   • Total filas en dataset principal: 1,314
   ✅ Integridad verificada: todas las filas están presentes

📋 Columnas disponibles en datasets por ciudad:
    1. Titulo
    2. Review
    3. TipoViaje
    4. Calificacion
    5. OrigenAutor
    6. FechaOpinion
    7. FechaEstadia
    8. Ciudad
    9. Atraccion
   10. TituloReview

📖 Muestra del dataset 'dataset_cdmx.csv':
Primeras 3 filas:
                                 Titulo                                                                                                                                                                                                                                                                                                                                                                                                                             Review  TipoViaje  Calificacion                    OrigenAutor FechaOpinion FechaEstadia Ciudad            Atraccion                                                                                                                                                                                                                                                                                                                                                                                                                                                          TituloReview
700  AVENIDA PRINCIPAL CIUDAD DE MÉXICO  Avenida Ciudad de México. Es mucho tiempo así que para caminar es necesario estar cerca del Ángel de la Independencia, Fuente Diana para que pueda disfrutar de los alrededores con tanto que hacer y ver. Castillo y parque de Chapultepec, hoteles y restaurantes de lujo, también informales. En el norte es un barrio residencial caro de lujo. Es imprescindible si viajas por la ciudad.  A 5 minutos de La Condesa y Roma.  Solitario             5                        anonimo   2025-09-01   2025-08-01   Cdmx  Paseo De La Reforma  AVENIDA PRINCIPAL CIUDAD DE MÉXICO Avenida Ciudad de México. Es mucho tiempo así que para caminar es necesario estar cerca del Ángel de la Independencia, Fuente Diana para que pueda disfrutar de los alrededores con tanto que hacer y ver. Castillo y parque de Chapultepec, hoteles y restaurantes de lujo, también informales. En el norte es un barrio residencial caro de lujo. Es imprescindible si viajas por la ciudad.  A 5 minutos de La Condesa y Roma.
701                           Hermoso 💚                                                                                                                                                                                                                                                                                                              Es hermoso su paisaje y recorrerlo, lo malo son sus manifestantes. No recomendaría ir en Mayo muchos manifestaciones.     Pareja             5  Santiago de Querétaro, México   2025-05-30   2025-05-01   Cdmx  Paseo De La Reforma                                                                                                                                                                                                                                                                                                                                       Hermoso 💚 Es hermoso su paisaje y recorrerlo, lo malo son sus manifestantes. No recomendaría ir en Mayo muchos manifestaciones.
702                       Sé consciente                  La foto de la entrada no coincide con esta ubicación. Es el ángel de la independencia no este lugar. Alguien tiene que quitar esa foto. Esta ubicación está llena de hermosas estatuas y fuentes. Mucha gente es robada aquí y escogida por todas partes. La gente te ve retirar dinero del cajero automático y trabajar en equipos para robarte. Advertencia. Cuanto más gente peor para el bolsillo de imágenes  Solitario             5                     Dallas, TX   2025-04-01   2025-04-01   Cdmx  Paseo De La Reforma                                       Sé consciente La foto de la entrada no coincide con esta ubicación. Es el ángel de la independencia no este lugar. Alguien tiene que quitar esa foto. Esta ubicación está llena de hermosas estatuas y fuentes. Mucha gente es robada aquí y escogida por todas partes. La gente te ve retirar dinero del cajero automático y trabajar en equipos para robarte. Advertencia. Cuanto más gente peor para el bolsillo de imágenes

🎯 DATASETS LISTOS PARA:
   • Análisis de sentimientos por ciudad
   • Comparaciones entre ciudades
   • Modelos de machine learning específicos
   • Visualizaciones personalizadas

📁 ESTRUCTURA FINAL:
   data/processed/datasets_por_ciudad/
   ├── dataset_cdmx.csv
   ├── dataset_cancun.csv

🎉 ¡2 datasets de ciudades listos para análisis!

✅ Verificación completada - Los datasets están listos para análisis de sentimientos