# Evidenciando Opiniones Mixtas: Análisis de Subjetividad y Objetividad por Frases

## Hipótesis de Investigación

**Problema identificado**: En el análisis previo de subjetividad, se obtuvo que solo el ~5% de las opiniones fueron clasificadas como objetivas, lo cual es menos de lo esperado considerando que las opiniones objetivas proporcionan información valiosa para los turistólogos.

**Hipótesis**: Las opiniones turísticas son frecuentemente **mixtas**, es decir, contienen tanto frases subjetivas (opiniones, emociones) como frases objetivas (información factual). El modelo de clasificación actual, entrenado en textos puramente objetivos o puramente subjetivos, tiende a clasificar textos mixtos como subjetivos, perdiendo así la información objetiva valiosa.

## Metodología para Validar la Hipótesis

1. **Segmentación de opiniones**: Usar un modelo de deep learning (WtP-Split) para dividir cada opinión en frases individuales
2. **Clasificación por frase**: Analizar la subjetividad de cada frase por separado
3. **Reclasificación de opiniones**: Clasificar cada opinión completa como:
   - **Subjetiva**: Solo contiene frases subjetivas
   - **Objetiva**: Solo contiene frases objetivas  
   - **Mixta**: Contiene al menos una frase objetiva Y una frase subjetiva
4. **Análisis de resultados**: Determinar qué porcentaje de opiniones son realmente mixtas

## Objetivo

Demostrar si existe un porcentaje significativo de opiniones mixtas que están siendo mal clasificadas, lo que explicaría la baja proporción de opiniones objetivas en el análisis inicial.

In [8]:
# Importar módulos necesarios
import sys
import os
from pathlib import Path

sys.path.append('../scripts')

from subjetividad import (
    cargar_dataset_para_subjetividad,
    mostrar_info_dataset,
    verificar_compatibilidad_cuda,
    analizar_opiniones_mixtas,
    visualizar_distribucion_tipos,
    mostrar_resumen_ejecutivo,
    mostrar_conclusiones_hipotesis,
    AnalizadorOpinionesMixtas,
    actualizar_dataset_principal
)

print(f"CUDA disponible: {verificar_compatibilidad_cuda()}")
print("✅ Módulos importados correctamente")

# Demostración de segmentación de frases con ejemplo
from wtpsplit import SaT
import torch

opinion_mixta = """Me encantó este lugar, es increíble y lo recomiendo mucho. 
El museo abre de 9:00 AM a 6:00 PM todos los días. 
La entrada cuesta 150 pesos por persona. 
Excelente atención al cliente, muy amables todos."""

print(f"\n📝 Opinión mixta de ejemplo:")
print(f'"{opinion_mixta}"')

# Configurar segmentador
sat_sm = SaT("sat-3l-sm")
if torch.cuda.is_available():
    sat_sm.half().to("cuda")

# Segmentar la opinión
frases_segmentadas = sat_sm.split(opinion_mixta)

print(f"\n📊 Total de frases detectadas: {len(frases_segmentadas)}")
for i, frase in enumerate(frases_segmentadas, 1):
    frase_limpia = frase.strip()
    if frase_limpia:
        print(f"  {i}. '{frase_limpia}'")

CUDA disponible: True
✅ Módulos importados correctamente

📝 Opinión mixta de ejemplo:
"Me encantó este lugar, es increíble y lo recomiendo mucho.
El museo abre de 9:00 AM a 6:00 PM todos los días.
La entrada cuesta 150 pesos por persona.
Excelente atención al cliente, muy amables todos."

📊 Total de frases detectadas: 7
  1. 'Me encantó este lugar, es increíble y lo recomiendo mucho.'
  3. 'El museo abre de 9:00 AM a 6:00 PM todos los días.'
  5. 'La entrada cuesta 150 pesos por persona.'
  7. 'Excelente atención al cliente, muy amables todos.'

In [2]:
# Cargar dataset principal con análisis completo
import pandas as pd

# Usar directamente el dataset principal 
ruta_dataset_principal = '../data/processed/dataset_opiniones_analisis.csv'

try:
    df = pd.read_csv(ruta_dataset_principal)
    fuente_datos = f"Dataset principal completo (desde {ruta_dataset_principal})"
    print(f"✅ Dataset cargado exitosamente desde archivo principal")
except FileNotFoundError:
    print(f"❌ Error: No se encontró el archivo {ruta_dataset_principal}")
    print(f"🔄 Verificar que existe el archivo dataset_opiniones_analisis.csv")
    # Fallback al método del módulo
    df, fuente_datos = cargar_dataset_para_subjetividad('../data/processed/')

mostrar_info_dataset(df, fuente_datos)
df.head()

✅ Dataset cargado exitosamente desde archivo principal
📊 Dataset cargado: 2464 filas | Fuente: Dataset principal completo (desde ../data/processed/dataset_opiniones_analisis.csv)
📋 Distribución de subjetividad (SubjetividadConHF):
   • Subjetivo: 2272 (92.2%)
   • Objetivo: 192 (7.8%)

,Titulo,Review,Calificacion,FechaEstadia,Ciudad,Atraccion,TituloReview,SentimientoPorCalificacion,SentimientoPorHF,SentimientoPorCardiff,SubjetividadConHF
0,¡Divertido y seguro!,"Estoy muy impresionado con Mazatlán, Mx. . La ...",5,2025-08-01,Mazatlan,Malecon De Mazatlan,¡Divertido y seguro!. Estoy muy impresionado c...,Positivo,Positivo,Positivo,Subjetivo
1,Un mes en Mazatlán,Acabamos de pasar un mes en Mazatlán. No estoy...,3,2025-01-01,Mazatlan,Malecon De Mazatlan,Un mes en Mazatlán. Acabamos de pasar un mes e...,Neutro,Negativo,Negativo,Subjetivo
2,Maravilloso,"Ubicado en la zona más turística de Mazatlán, ...",5,2025-01-01,Mazatlan,Malecon De Mazatlan,Maravilloso. Ubicado en la zona más turística ...,Positivo,Positivo,Positivo,Subjetivo
3,Caminando por el Malecón,Hermoso El Malecón de Mazatlán he caminado en ...,5,2024-12-01,Mazatlan,Malecon De Mazatlan,Caminando por el Malecón. Hermoso El Malecón d...,Positivo,Positivo,Positivo,Subjetivo
4,"Nunca más, por desgracia","Mazatlán no es seguro. Lamento escribir esto, ...",1,2024-12-01,Mazatlan,Malecon De Mazatlan,"Nunca más, por desgracia. Mazatlán no es segur...",Negativo,Negativo,Negativo,Subjetivo

In [5]:
# Análisis completo de opiniones mixtas usando módulo especializado
MUESTRA_ANALISIS = len(df)  # Usar dataset completo o cambiar por número menor para pruebas

# Aplicar análisis modular
df_analisis = analizar_opiniones_mixtas(
    df.sample(min(MUESTRA_ANALISIS, len(df)), random_state=42) if MUESTRA_ANALISIS < len(df) else df,
    columna_texto='TituloReview',
    mostrar_ejemplos=True,
    n_ejemplos=3
)

Device set to use cuda:0

🔄 Procesando lote 1-10 de 2464 opiniones...
🔄 Procesando lote 11-20 de 2464 opiniones...
🔄 Procesando lote 21-30 de 2464 opiniones...
🔄 Procesando lote 31-40 de 2464 opiniones...
🔄 Procesando lote 41-50 de 2464 opiniones...
🔄 Procesando lote 51-60 de 2464 opiniones...
🔄 Procesando lote 61-70 de 2464 opiniones...
🔄 Procesando lote 71-80 de 2464 opiniones...
🔄 Procesando lote 81-90 de 2464 opiniones...
🔄 Procesando lote 91-100 de 2464 opiniones...
🔄 Procesando lote 101-110 de 2464 opiniones...
🔄 Procesando lote 111-120 de 2464 opiniones...
🔄 Procesando lote 121-130 de 2464 opiniones...
🔄 Procesando lote 131-140 de 2464 opiniones...
🔄 Procesando lote 141-150 de 2464 opiniones...
🔄 Procesando lote 151-160 de 2464 opiniones...
🔄 Procesando lote 161-170 de 2464 opiniones...
🔄 Procesando lote 171-180 de 2464 opiniones...
🔄 Procesando lote 181-190 de 2464 opiniones...
🔄 Procesando lote 191-200 de 2464 opiniones...
🔄 Procesando lote 201-210 de 2464 opiniones...
🔄 Procesando lote 211-220 de 2464 opiniones...
🔄 Procesando lote 221-230 de 2464 opiniones...
🔄 Procesando lote 231-240 de 2464 opiniones...
🔄 Procesando lote 241-250 de 2464 opiniones...
🔄 Procesando lote 251-260 de 2464 opiniones...
🔄 Procesando lote 261-270 de 2464 opiniones...
🔄 Procesando lote 271-280 de 2464 opiniones...
🔄 Procesando lote 281-290 de 2464 opiniones...
🔄 Procesando lote 291-300 de 2464 opiniones...
🔄 Procesando lote 301-310 de 2464 opiniones...
🔄 Procesando lote 311-320 de 2464 opiniones...
🔄 Procesando lote 321-330 de 2464 opiniones...
🔄 Procesando lote 331-340 de 2464 opiniones...
🔄 Procesando lote 341-350 de 2464 opiniones...
🔄 Procesando lote 351-360 de 2464 opiniones...
🔄 Procesando lote 361-370 de 2464 opiniones...
🔄 Procesando lote 371-380 de 2464 opiniones...
🔄 Procesando lote 381-390 de 2464 opiniones...
🔄 Procesando lote 391-400 de 2464 opiniones...
🔄 Procesando lote 401-410 de 2464 opiniones...
🔄 Procesando lote 411-420 de 2464 opiniones...
🔄 Procesando lote 421-430 de 2464 opiniones...
🔄 Procesando lote 431-440 de 2464 opiniones...
🔄 Procesando lote 441-450 de 2464 opiniones...
🔄 Procesando lote 451-460 de 2464 opiniones...
🔄 Procesando lote 461-470 de 2464 opiniones...
🔄 Procesando lote 471-480 de 2464 opiniones...
🔄 Procesando lote 481-490 de 2464 opiniones...
🔄 Procesando lote 491-500 de 2464 opiniones...
🔄 Procesando lote 501-510 de 2464 opiniones...
🔄 Procesando lote 511-520 de 2464 opiniones...
🔄 Procesando lote 521-530 de 2464 opiniones...
🔄 Procesando lote 531-540 de 2464 opiniones...
🔄 Procesando lote 541-550 de 2464 opiniones...
🔄 Procesando lote 551-560 de 2464 opiniones...
🔄 Procesando lote 561-570 de 2464 opiniones...
🔄 Procesando lote 571-580 de 2464 opiniones...
🔄 Procesando lote 581-590 de 2464 opiniones...
🔄 Procesando lote 591-600 de 2464 opiniones...
🔄 Procesando lote 601-610 de 2464 opiniones...
🔄 Procesando lote 611-620 de 2464 opiniones...
🔄 Procesando lote 621-630 de 2464 opiniones...
🔄 Procesando lote 631-640 de 2464 opiniones...
🔄 Procesando lote 641-650 de 2464 opiniones...
🔄 Procesando lote 651-660 de 2464 opiniones...
🔄 Procesando lote 661-670 de 2464 opiniones...
🔄 Procesando lote 671-680 de 2464 opiniones...
🔄 Procesando lote 681-690 de 2464 opiniones...
🔄 Procesando lote 691-700 de 2464 opiniones...
🔄 Procesando lote 701-710 de 2464 opiniones...
🔄 Procesando lote 711-720 de 2464 opiniones...
🔄 Procesando lote 721-730 de 2464 opiniones...
🔄 Procesando lote 731-740 de 2464 opiniones...
🔄 Procesando lote 741-750 de 2464 opiniones...
🔄 Procesando lote 751-760 de 2464 opiniones...
🔄 Procesando lote 761-770 de 2464 opiniones...
🔄 Procesando lote 771-780 de 2464 opiniones...
🔄 Procesando lote 781-790 de 2464 opiniones...
🔄 Procesando lote 791-800 de 2464 opiniones...
🔄 Procesando lote 801-810 de 2464 opiniones...
🔄 Procesando lote 811-820 de 2464 opiniones...
🔄 Procesando lote 821-830 de 2464 opiniones...
🔄 Procesando lote 831-840 de 2464 opiniones...
🔄 Procesando lote 841-850 de 2464 opiniones...
🔄 Procesando lote 851-860 de 2464 opiniones...
🔄 Procesando lote 861-870 de 2464 opiniones...
🔄 Procesando lote 871-880 de 2464 opiniones...
🔄 Procesando lote 881-890 de 2464 opiniones...
🔄 Procesando lote 891-900 de 2464 opiniones...
🔄 Procesando lote 901-910 de 2464 opiniones...
🔄 Procesando lote 911-920 de 2464 opiniones...
🔄 Procesando lote 921-930 de 2464 opiniones...
🔄 Procesando lote 931-940 de 2464 opiniones...
🔄 Procesando lote 941-950 de 2464 opiniones...
🔄 Procesando lote 951-960 de 2464 opiniones...
🔄 Procesando lote 961-970 de 2464 opiniones...
🔄 Procesando lote 971-980 de 2464 opiniones...
🔄 Procesando lote 981-990 de 2464 opiniones...
🔄 Procesando lote 991-1000 de 2464 opiniones...
🔄 Procesando lote 1001-1010 de 2464 opiniones...
🔄 Procesando lote 1011-1020 de 2464 opiniones...
🔄 Procesando lote 1021-1030 de 2464 opiniones...
🔄 Procesando lote 1031-1040 de 2464 opiniones...
🔄 Procesando lote 1041-1050 de 2464 opiniones...
🔄 Procesando lote 1051-1060 de 2464 opiniones...
🔄 Procesando lote 1061-1070 de 2464 opiniones...
🔄 Procesando lote 1071-1080 de 2464 opiniones...
🔄 Procesando lote 1081-1090 de 2464 opiniones...
🔄 Procesando lote 1091-1100 de 2464 opiniones...
🔄 Procesando lote 1101-1110 de 2464 opiniones...
🔄 Procesando lote 1111-1120 de 2464 opiniones...
🔄 Procesando lote 1121-1130 de 2464 opiniones...
🔄 Procesando lote 1131-1140 de 2464 opiniones...
🔄 Procesando lote 1141-1150 de 2464 opiniones...
🔄 Procesando lote 1151-1160 de 2464 opiniones...
🔄 Procesando lote 1161-1170 de 2464 opiniones...
🔄 Procesando lote 1171-1180 de 2464 opiniones...
🔄 Procesando lote 1181-1190 de 2464 opiniones...
🔄 Procesando lote 1191-1200 de 2464 opiniones...
🔄 Procesando lote 1201-1210 de 2464 opiniones...
🔄 Procesando lote 1211-1220 de 2464 opiniones...
🔄 Procesando lote 1221-1230 de 2464 opiniones...
🔄 Procesando lote 1231-1240 de 2464 opiniones...
🔄 Procesando lote 1241-1250 de 2464 opiniones...
🔄 Procesando lote 1251-1260 de 2464 opiniones...
🔄 Procesando lote 1261-1270 de 2464 opiniones...
🔄 Procesando lote 1271-1280 de 2464 opiniones...
🔄 Procesando lote 1281-1290 de 2464 opiniones...
🔄 Procesando lote 1291-1300 de 2464 opiniones...
🔄 Procesando lote 1301-1310 de 2464 opiniones...
🔄 Procesando lote 1311-1320 de 2464 opiniones...
🔄 Procesando lote 1321-1330 de 2464 opiniones...
🔄 Procesando lote 1331-1340 de 2464 opiniones...
🔄 Procesando lote 1341-1350 de 2464 opiniones...
🔄 Procesando lote 1351-1360 de 2464 opiniones...
🔄 Procesando lote 1361-1370 de 2464 opiniones...
🔄 Procesando lote 1371-1380 de 2464 opiniones...
🔄 Procesando lote 1381-1390 de 2464 opiniones...
🔄 Procesando lote 1391-1400 de 2464 opiniones...
🔄 Procesando lote 1401-1410 de 2464 opiniones...
🔄 Procesando lote 1411-1420 de 2464 opiniones...
🔄 Procesando lote 1421-1430 de 2464 opiniones...
🔄 Procesando lote 1431-1440 de 2464 opiniones...
🔄 Procesando lote 1441-1450 de 2464 opiniones...
🔄 Procesando lote 1451-1460 de 2464 opiniones...
🔄 Procesando lote 1461-1470 de 2464 opiniones...
🔄 Procesando lote 1471-1480 de 2464 opiniones...
🔄 Procesando lote 1481-1490 de 2464 opiniones...
🔄 Procesando lote 1491-1500 de 2464 opiniones...
🔄 Procesando lote 1501-1510 de 2464 opiniones...
🔄 Procesando lote 1511-1520 de 2464 opiniones...
🔄 Procesando lote 1521-1530 de 2464 opiniones...
🔄 Procesando lote 1531-1540 de 2464 opiniones...
🔄 Procesando lote 1541-1550 de 2464 opiniones...
🔄 Procesando lote 1551-1560 de 2464 opiniones...
🔄 Procesando lote 1561-1570 de 2464 opiniones...
🔄 Procesando lote 1571-1580 de 2464 opiniones...
🔄 Procesando lote 1581-1590 de 2464 opiniones...
🔄 Procesando lote 1591-1600 de 2464 opiniones...
🔄 Procesando lote 1601-1610 de 2464 opiniones...
🔄 Procesando lote 1611-1620 de 2464 opiniones...
🔄 Procesando lote 1621-1630 de 2464 opiniones...
🔄 Procesando lote 1631-1640 de 2464 opiniones...
🔄 Procesando lote 1641-1650 de 2464 opiniones...
🔄 Procesando lote 1651-1660 de 2464 opiniones...
🔄 Procesando lote 1661-1670 de 2464 opiniones...
🔄 Procesando lote 1671-1680 de 2464 opiniones...
🔄 Procesando lote 1681-1690 de 2464 opiniones...
🔄 Procesando lote 1691-1700 de 2464 opiniones...
🔄 Procesando lote 1701-1710 de 2464 opiniones...
🔄 Procesando lote 1711-1720 de 2464 opiniones...
🔄 Procesando lote 1721-1730 de 2464 opiniones...
🔄 Procesando lote 1731-1740 de 2464 opiniones...
🔄 Procesando lote 1741-1750 de 2464 opiniones...
🔄 Procesando lote 1751-1760 de 2464 opiniones...
🔄 Procesando lote 1761-1770 de 2464 opiniones...
🔄 Procesando lote 1771-1780 de 2464 opiniones...
🔄 Procesando lote 1781-1790 de 2464 opiniones...
🔄 Procesando lote 1791-1800 de 2464 opiniones...
🔄 Procesando lote 1801-1810 de 2464 opiniones...
🔄 Procesando lote 1811-1820 de 2464 opiniones...
🔄 Procesando lote 1821-1830 de 2464 opiniones...
🔄 Procesando lote 1831-1840 de 2464 opiniones...
🔄 Procesando lote 1841-1850 de 2464 opiniones...
🔄 Procesando lote 1851-1860 de 2464 opiniones...
🔄 Procesando lote 1861-1870 de 2464 opiniones...
🔄 Procesando lote 1871-1880 de 2464 opiniones...
🔄 Procesando lote 1881-1890 de 2464 opiniones...
🔄 Procesando lote 1891-1900 de 2464 opiniones...
🔄 Procesando lote 1901-1910 de 2464 opiniones...
🔄 Procesando lote 1911-1920 de 2464 opiniones...
🔄 Procesando lote 1921-1930 de 2464 opiniones...
🔄 Procesando lote 1931-1940 de 2464 opiniones...
🔄 Procesando lote 1941-1950 de 2464 opiniones...
🔄 Procesando lote 1951-1960 de 2464 opiniones...
🔄 Procesando lote 1961-1970 de 2464 opiniones...
🔄 Procesando lote 1971-1980 de 2464 opiniones...
🔄 Procesando lote 1981-1990 de 2464 opiniones...
🔄 Procesando lote 1991-2000 de 2464 opiniones...
🔄 Procesando lote 2001-2010 de 2464 opiniones...
🔄 Procesando lote 2011-2020 de 2464 opiniones...
🔄 Procesando lote 2021-2030 de 2464 opiniones...
🔄 Procesando lote 2031-2040 de 2464 opiniones...
🔄 Procesando lote 2041-2050 de 2464 opiniones...
🔄 Procesando lote 2051-2060 de 2464 opiniones...
🔄 Procesando lote 2061-2070 de 2464 opiniones...
🔄 Procesando lote 2071-2080 de 2464 opiniones...
🔄 Procesando lote 2081-2090 de 2464 opiniones...
🔄 Procesando lote 2091-2100 de 2464 opiniones...
🔄 Procesando lote 2101-2110 de 2464 opiniones...
🔄 Procesando lote 2111-2120 de 2464 opiniones...
🔄 Procesando lote 2121-2130 de 2464 opiniones...
🔄 Procesando lote 2131-2140 de 2464 opiniones...
🔄 Procesando lote 2141-2150 de 2464 opiniones...
🔄 Procesando lote 2151-2160 de 2464 opiniones...
🔄 Procesando lote 2161-2170 de 2464 opiniones...
🔄 Procesando lote 2171-2180 de 2464 opiniones...
🔄 Procesando lote 2181-2190 de 2464 opiniones...
🔄 Procesando lote 2191-2200 de 2464 opiniones...
🔄 Procesando lote 2201-2210 de 2464 opiniones...
🔄 Procesando lote 2211-2220 de 2464 opiniones...
🔄 Procesando lote 2221-2230 de 2464 opiniones...
🔄 Procesando lote 2231-2240 de 2464 opiniones...
🔄 Procesando lote 2241-2250 de 2464 opiniones...
🔄 Procesando lote 2251-2260 de 2464 opiniones...
🔄 Procesando lote 2261-2270 de 2464 opiniones...
🔄 Procesando lote 2271-2280 de 2464 opiniones...
🔄 Procesando lote 2281-2290 de 2464 opiniones...
🔄 Procesando lote 2291-2300 de 2464 opiniones...
🔄 Procesando lote 2301-2310 de 2464 opiniones...
🔄 Procesando lote 2311-2320 de 2464 opiniones...
🔄 Procesando lote 2321-2330 de 2464 opiniones...
🔄 Procesando lote 2331-2340 de 2464 opiniones...
🔄 Procesando lote 2341-2350 de 2464 opiniones...
🔄 Procesando lote 2351-2360 de 2464 opiniones...
🔄 Procesando lote 2361-2370 de 2464 opiniones...
🔄 Procesando lote 2371-2380 de 2464 opiniones...
🔄 Procesando lote 2381-2390 de 2464 opiniones...
🔄 Procesando lote 2391-2400 de 2464 opiniones...
🔄 Procesando lote 2401-2410 de 2464 opiniones...
🔄 Procesando lote 2411-2420 de 2464 opiniones...
🔄 Procesando lote 2421-2430 de 2464 opiniones...
🔄 Procesando lote 2431-2440 de 2464 opiniones...
🔄 Procesando lote 2441-2450 de 2464 opiniones...
🔄 Procesando lote 2451-2460 de 2464 opiniones...
🔄 Procesando lote 2461-2464 de 2464 opiniones...
✅ Procesamiento completo.
📊 ANÁLISIS DE OPINIONES MIXTAS
==================================================
📈 Total opiniones: 2464

📋 DISTRIBUCIÓN POR TIPOS:
• Mixta: 1574 (63.9%)
• Subjetivo: 827 (33.6%)
• Objetivo: 63 (2.6%)

📊 ESTADÍSTICAS DE FRASES:
• Total frases: 11636
• Subjetivas: 7459 (64.1%)
• Objetivas: 4177 (35.9%)
• Promedio por opinión: 4.7

🔀 CARACTERÍSTICAS OPINIONES MIXTAS:
• Total: 1574 (63.9%)
• Promedio frases: 5.6
• Promedio subjetivo: 56.3%
• Promedio objetivo: 43.7%

🎯 VALIDACIÓN DE HIPÓTESIS
========================================
✅ HIPÓTESIS CONFIRMADA: 63.9% de opiniones son mixtas
📊 Las opiniones mixtas representan una proporción significativa
💡 Combinan información emocional con datos útiles para turistólogos

📈 Metodología validada:
• Segmentación automática con WtP-Split
• Clasificación por frases individuales
• Identificación exitosa de contenido híbrido

🔍 EJEMPLOS DE OPINIONES MIXTAS
============================================================

🎯 EJEMPLO 1:
📝 Opinión: "Nice refreshing water to swim in. The waves are nice and there is marked places to swim. No lifeguards on duty though. The sun gets hot by 10 am so the water is your friend."
📊 4 frases | 2 subjetivas | 2 objetivas
📈 50.0% subjetivo, 50.0% objetivo
📋 Desglose por frases:
   💭 1. [Subjetivo] "Nice refreshing water to swim in."
   📊 2. [Objetivo] "The waves are nice and there is marked places to swim."
   📊 3. [Objetivo] "No lifeguards on duty though."
   💭 4. [Subjetivo] "The sun gets hot by 10 am so the water is your friend."

🎯 EJEMPLO 2:
📝 Opinión: "Diseño vanguardista. El diseño del hotel es de lo mejor, se logran excelentes fotos en el remolino de agua y al exterior del museo, muy bonito y aprendes sobre el barroco.Los contras: considero que es un poco caro, no dejan tomar fotos a las obras de arte."
📊 3 frases | 2 subjetivas | 1 objetivas
📈 66.7% subjetivo, 33.3% objetivo
📋 Desglose por frases:
   💭 1. [Subjetivo] "Diseño vanguardista."
   💭 2. [Subjetivo] "El diseño del hotel es de lo mejor, se logran excelentes fotos en e..."
   📊 3. [Objetivo] "Los contras: considero que es un poco caro, no dejan tomar fotos a ..."

🎯 EJEMPLO 3:
📝 Opinión: "Nueva y súper experiencia en la Marina. Por primera vez este año, alquilamos un hermoso condominio en el área de Marina de PV por un mes. Es hermoso ~ cerca de muchos restaurantes, tiendas, librerías y mucho más. Todos los jueves por la noche hay un mercado muy grande instalado a lo largo del paseo marítimo. . . . mucho que ver y "comprar". La gente es amigable y estamos disfrutando de una estadía maravillosa en nuestro hermoso condominio."
📊 6 frases | 4 subjetivas | 2 objetivas
📈 66.7% subjetivo, 33.3% objetivo
📋 Desglose por frases:
   💭 1. [Subjetivo] "Nueva y súper experiencia en la Marina."
   📊 2. [Objetivo] "Por primera vez este año, alquilamos un hermoso condominio en el ár..."
   💭 3. [Subjetivo] "Es hermoso ~ cerca de muchos restaurantes, tiendas, librerías y muc..."
   📊 4. [Objetivo] "Todos los jueves por la noche hay un mercado muy grande instalado a..."
   💭 5. [Subjetivo] ". . . mucho que ver y "comprar"."
   💭 6. [Subjetivo] "La gente es amigable y estamos disfrutando de una estadía maravillo..."

In [9]:
# Visualización de distribución de tipos de opiniones
visualizar_distribucion_tipos(df_analisis)

KeyError: 'TipoOpinion'

In [10]:
# Resumen ejecutivo y validación de hipótesis

# Calcular estadísticas y validar hipótesis
analizador = AnalizadorOpinionesMixtas()
estadisticas = analizador.obtener_estadisticas_mixtas(df_analisis)
validacion = analizador.validar_hipotesis(estadisticas)

# Mostrar resultados finales
mostrar_resumen_ejecutivo(estadisticas)
mostrar_conclusiones_hipotesis(validacion, estadisticas)

🎯 RESUMEN EJECUTIVO - ANÁLISIS DE OPINIONES MIXTAS
============================================================
📊 RESULTADOS PRINCIPALES:
• Total opiniones analizadas: 2464
• Opiniones mixtas identificadas: 1574 (63.9%)

📋 DISTRIBUCIÓN POR TIPOS:
• Mixta: 1574 (63.9%)
• Subjetivo: 827 (33.6%)
• Objetivo: 63 (2.6%)

🔍 ANÁLISIS GRANULAR:
• Total frases analizadas: 11636
• Promedio frases por opinión: 4.7
• Distribución: 64.1% subjetivas, 35.9% objetivas

💡 IMPLICACIONES PARA TURISTOLOGÍA:
• Las opiniones mixtas representan una fuente significativa de información
• Combinan percepciones emocionales con datos prácticos útiles
• Metodología validada para extracción de contenido híbrido

✅ Metodología aplicada exitosamente: Segmentación + Clasificación por frases

🔬 CONCLUSIONES SOBRE LA HIPÓTESIS
==================================================
✅ HIPÓTESIS CONFIRMADA: 63.9% de opiniones son mixtas

✅ EVIDENCIA ENCONTRADA:
• 63.9% de opiniones contienen contenido mixto
• Las opiniones mixtas combinan información emocional y factual
• El análisis granular revela contenido híbrido no detectado previamente
• Composición promedio: 56.3% subjetivo, 43.7% objetivo

🎯 METODOLOGÍA VALIDADA:
• Segmentación automática de oraciones con modelos de deep learning
• Clasificación individual de frases para análisis granular
• Identificación exitosa de patrones de contenido híbrido
• Herramienta útil para análisis detallado de opiniones turísticas

In [11]:
# Dataset final con análisis de opiniones mixtas
columnas_relevantes = ['TituloReview', 'TotalFrases', 'FrasesSubjetivas', 'FrasesObjetivas', 'SubjetividadConFrases', 'EsMixta']

if 'ClasificacionSubjetividadConHF' in df_analisis.columns:
    columnas_relevantes.insert(-2, 'ClasificacionSubjetividadConHF')

print(f"📊 Dataset final: {len(df_analisis)} opiniones con análisis granular por frases")
df_analisis[columnas_relevantes].head(10)

📊 Dataset final: 2464 opiniones con análisis granular por frases

,TituloReview,TotalFrases,FrasesSubjetivas,FrasesObjetivas,SubjetividadConFrases,EsMixta
0,¡Divertido y seguro!. Estoy muy impresionado c...,8,6,2,Mixta,True
1,Un mes en Mazatlán. Acabamos de pasar un mes e...,30,12,18,Mixta,True
2,Maravilloso. Ubicado en la zona más turística ...,3,2,1,Mixta,True
3,Caminando por el Malecón. Hermoso El Malecón d...,2,1,1,Mixta,True
4,"Nunca más, por desgracia. Mazatlán no es segur...",9,4,5,Mixta,True
5,"Tranquilo. Es enorme y con muchas esculturas, ...",3,2,1,Mixta,True
6,Espectacular. Todo me Encanto. Las comidas el ...,6,5,1,Mixta,True
7,Hermosa zona y gente maravillosa!. Bajamos dur...,4,4,0,Subjetivo,False
8,Caminando por el malecón. Caminamos desde el á...,6,4,2,Mixta,True
9,Paseo en familia. Un paseo excelente! La playa...,3,2,1,Mixta,True

In [12]:
# Actualizar dataset principal con la nueva columna SubjetividadConFrases
ruta_dataset_principal = '../data/processed/dataset_opiniones_analisis.csv'

# Usar función del módulo para actualizar el dataset de manera limpia
exito = actualizar_dataset_principal(
    df_analisis=df_analisis,
    ruta_dataset_principal=ruta_dataset_principal,
    nueva_columna='SubjetividadConFrases'
)

if exito:
    print(f"\n📁 Archivo actualizado: {ruta_dataset_principal}")
else:
    print("\n❌ Error al actualizar el dataset principal")

📂 Actualizando dataset principal...
✅ Dataset principal actualizado exitosamente en: ../data/processed/dataset_opiniones_analisis.csv
📊 Total de registros: 2464
🆕 Nueva columna agregada: SubjetividadConFrases

📈 Distribución de SubjetividadConFrases:
   Mixta: 1574 opiniones (63.9%)
   Subjetivo: 827 opiniones (33.6%)
   Objetivo: 63 opiniones (2.6%)

🔍 Comparación SubjetividadConHF vs SubjetividadConFrases:
SubjetividadConFrases  Mixta  Objetivo  Subjetivo   All
SubjetividadConHF
Objetivo                 142        50          0   192
Subjetivo               1432        13        827  2272
All                     1574        63        827  2464

📋 Columnas finales en el dataset (12 total):
   • Titulo
   • Review
   • Calificacion
   • FechaEstadia
   • Ciudad
   • Atraccion
   • TituloReview
   • SentimientoPorCalificacion
   • SentimientoPorHF
   • SentimientoPorCardiff
   • SubjetividadConHF
   • SubjetividadConFrases

🗑️ Columnas temporales eliminadas: TotalFrases, FrasesSubjetivas, FrasesObjetivas, TipoOpinion, EsMixta, PorcentajeSubjetivo, PorcentajeObjetivo
🔄 Dataset listo para ser usado en análisis posteriores

📁 Archivo actualizado: ../data/processed/dataset_opiniones_analisis.csv